//! Migration fixtures, each paired with the manifest it must produce.
//!
//! The comparison is exact, so a change in translation shows up as a diff in a
//! reviewable file rather than as a changed assertion (SPEC §11.5). The version
//! header is checked separately: it carries the jrs version, which would make the
//! fixture stale on every release.

mod common;

use std::path::{Path, PathBuf};

use common::{FixtureRepo, Scratch, copy_dir, fixtures};
use jrs::manifest::Manifest;
use jrs::migrate::{self, Migration, Source};
use jrs::resolve::{self, Classpath};

fn migrate_fixture(name: &str) -> (Migration, PathBuf) {
    let dir = fixtures().join("migrate").join(name);
    (migrate::plan(&dir, None).unwrap(), dir)
}

fn expected(dir: &Path) -> String {
    std::fs::read_to_string(dir.join("expected-jrs.toml")).unwrap()
}

#[test]
fn the_maven_fixture_translates_exactly() {
    let (migration, dir) = migrate_fixture("maven");
    assert_eq!(migration.source, Source::Maven);
    assert_eq!(migration.manifest.render(None), expected(&dir));
}

#[test]
fn the_gradle_fixture_translates_exactly() {
    let (migration, dir) = migrate_fixture("gradle");
    assert_eq!(migration.source, Source::Gradle);
    assert_eq!(migration.manifest.render(None), expected(&dir));
}

#[test]
fn every_expected_manifest_is_a_manifest_jrs_can_read() {
    for name in ["maven", "gradle"] {
        let (migration, dir) = migrate_fixture(name);
        let text = migration.render_manifest();
        let parsed = Manifest::parse(&text, &dir.join("jrs.toml"), &dir).unwrap();
        assert!(
            parsed.warnings.is_empty(),
            "{name} produced a manifest with warnings: {:?}",
            parsed.warnings
        );
        assert!(text.starts_with("# Generated by jrs "));
    }
}

#[test]
fn the_maven_report_names_what_it_could_not_translate() {
    let (migration, _) = migrate_fixture("maven");
    let skipped = migration.report.not_migrated.join("\n");

    // Each of these is in the fixture precisely so the report is exercised.
    assert!(skipped.contains("jakarta.servlet-api"), "{skipped}");
    assert!(skipped.contains("provided"), "{skipped}");
    assert!(skipped.contains("lombok"), "{skipped}");
    assert!(skipped.contains("optional"), "{skipped}");
    assert!(skipped.contains("maven-antrun-plugin"), "{skipped}");
    assert!(skipped.contains("ci"), "the inactive profile: {skipped}");

    let review = migration.report.needs_review.join("\n");
    assert!(review.contains("clamped to 1.2"), "{review}");

    // ...and the understood plugins are not complained about.
    assert!(!skipped.contains("maven-jar-plugin"), "{skipped}");
    assert!(!skipped.contains("maven-compiler-plugin"), "{skipped}");
}

#[test]
fn the_gradle_report_opens_by_admitting_it_is_approximate() {
    let (migration, _) = migrate_fixture("gradle");
    let preamble = migration.report.preamble.as_deref().unwrap();
    assert!(preamble.contains("approximate"), "{preamble}");
    assert!(preamble.contains("review"), "{preamble}");

    let skipped = migration.report.not_migrated.join("\n");
    assert!(skipped.contains("annotationProcessor"), "{skipped}");
    assert!(skipped.contains("sharedVersion"), "{skipped}");
    assert!(skipped.contains("does.not.exist"), "{skipped}");
    assert!(skipped.contains("core, web"), "{skipped}");
    assert!(skipped.contains("checkstyle"), "{skipped}");
    assert!(skipped.contains("custom tasks"), "{skipped}");
}

#[test]
fn migration_writes_one_file_and_touches_nothing_else() {
    let scratch = Scratch::new("migrate-write");
    let dir = scratch.join("project");
    copy_dir(&fixtures().join("migrate/maven"), &dir);
    let before = std::fs::read_to_string(dir.join("pom.xml")).unwrap();

    let migration = migrate::plan(&dir, None).unwrap();
    let written = migrate::write(&migration, &dir, false).unwrap().unwrap();

    assert_eq!(written, dir.join("jrs.toml"));
    assert_eq!(
        std::fs::read_to_string(dir.join("pom.xml")).unwrap(),
        before,
        "the original build file must survive untouched"
    );

    // Refuses to clobber, unless told to.
    let error = migrate::write(&migration, &dir, false)
        .unwrap_err()
        .to_string();
    assert!(error.contains("--force"), "{error}");
    migrate::write(&migration, &dir, true).unwrap();
}

/// The round trip SPEC §11.5 asks for: migrate, then build, and check that the
/// resolved classpath matches a checked expectation.
#[test]
fn a_migrated_project_resolves_the_classpath_it_should() {
    let scratch = Scratch::new("migrate-round-trip");
    let fixture = FixtureRepo::new(&scratch);
    let dir = scratch.join("project");
    std::fs::create_dir_all(&dir).unwrap();

    // A pom.xml over the same coordinates the local repository fixture serves,
    // so the round trip stays hermetic.
    std::fs::write(
        dir.join("pom.xml"),
        format!(
            r#"<project>
  <groupId>org.example</groupId>
  <artifactId>migrated</artifactId>
  <version>1.0.0</version>
  <properties><maven.compiler.release>17</maven.compiler.release></properties>
  <dependencies>
    <dependency>
      <groupId>org.example</groupId><artifactId>lib</artifactId><version>1.0.0</version>
    </dependency>
  </dependencies>
  <repositories>
    <repository><id>fixture</id><url>{}</url></repository>
  </repositories>
</project>"#,
            jrs::resolve::repo::file_url(&fixture.root)
        ),
    )
    .unwrap();

    let migration = migrate::plan(&dir, None).unwrap();
    migrate::write(&migration, &dir, false).unwrap();

    let manifest = Manifest::load(dir.join("jrs.toml")).unwrap();
    assert_eq!(manifest.name, "migrated");
    assert_eq!(manifest.java.source, Some(17));

    let fetcher = fixture.fetcher();
    let mut resolution = resolve::resolve(&manifest, &fetcher, 4).unwrap();
    resolve::fetch_jars(&mut resolution, &fetcher, 4).unwrap();

    let names: Vec<String> = resolution
        .classpath(Classpath::Compile)
        .iter()
        .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
        .collect();
    assert_eq!(
        names,
        vec!["lib-1.0.0.jar", "core-1.0.0.jar"],
        "direct dependency first, then its transitive"
    );
}

#[test]
fn detection_reports_what_it_looked_for() {
    let scratch = Scratch::new("migrate-detect");
    let empty = scratch.join("empty");
    std::fs::create_dir_all(&empty).unwrap();

    let error = migrate::plan(&empty, None).unwrap_err();
    assert_eq!(error.exit_code(), 2, "detection failure is a usage error");
    let message = error.to_string();
    assert!(message.contains("pom.xml"), "{message}");
    assert!(message.contains("build.gradle"), "{message}");
}
