//! One-shot translation from Maven or Gradle into `jrs.toml`.
//!
//! This is deliberately not a compatibility layer (SPEC §11): it runs once,
//! writes one file, prints a report, and is then out of the picture. The original
//! build files are never touched, so a project can keep building with its old
//! tool while the migration is evaluated.

pub mod gradle;
pub mod maven;

use std::path::{Path, PathBuf};

use crate::error::{IoResultExt, JrsError, Result};
use crate::manifest::{MANIFEST_FILE, Manifest};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    Maven,
    Gradle,
}

impl Source {
    pub fn parse(s: &str) -> Result<Source> {
        match s.trim().to_ascii_lowercase().as_str() {
            "maven" => Ok(Source::Maven),
            "gradle" => Ok(Source::Gradle),
            other => Err(JrsError::usage(format!(
                "unknown build system `{other}`; expected `maven` or `gradle`"
            ))),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Source::Maven => "Maven",
            Source::Gradle => "Gradle",
        }
    }
}

/// What the translation did, could only do approximately, and refused to guess at.
#[derive(Debug, Default, Clone)]
pub struct Report {
    /// Printed before the three blocks; Gradle uses it to say the translation is
    /// approximate.
    pub preamble: Option<String>,
    pub migrated: Vec<String>,
    pub needs_review: Vec<String>,
    pub not_migrated: Vec<String>,
}

impl Report {
    pub fn migrated(&mut self, what: impl Into<String>) {
        self.migrated.push(what.into());
    }
    pub fn review(&mut self, what: impl Into<String>) {
        self.needs_review.push(what.into());
    }
    pub fn skipped(&mut self, what: impl Into<String>) {
        self.not_migrated.push(what.into());
    }
}

#[derive(Debug, Clone)]
pub struct Migration {
    pub source: Source,
    /// The build file the manifest was translated from.
    pub source_file: PathBuf,
    pub manifest: Manifest,
    pub report: Report,
}

impl Migration {
    /// The comment header that goes at the top of the generated manifest.
    pub fn header(&self) -> String {
        format!(
            "Generated by jrs {} from {}.\n\
             Review it before relying on it: translation is best-effort, and\n\
             the original build file was left untouched.",
            env!("CARGO_PKG_VERSION"),
            self.source_file
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_else(|| self.source_file.display().to_string()),
        )
    }

    pub fn render_manifest(&self) -> String {
        self.manifest.render(Some(&self.header()))
    }
}

/// Which build system a directory holds (SPEC §11.1).
pub fn detect(dir: &Path) -> Result<(Source, PathBuf)> {
    let pom = dir.join("pom.xml");
    let gradle_groovy = dir.join("build.gradle");
    let gradle_kts = dir.join("build.gradle.kts");

    let maven = pom.is_file();
    let gradle = gradle_groovy.is_file() || gradle_kts.is_file();

    match (maven, gradle) {
        (true, false) => Ok((Source::Maven, pom)),
        (false, true) => Ok((
            Source::Gradle,
            if gradle_groovy.is_file() {
                gradle_groovy
            } else {
                gradle_kts
            },
        )),
        (true, true) => Err(JrsError::usage(format!(
            "{} holds both a pom.xml and a Gradle build\n\n\
             say which one to read: `jrs migrate --from maven` or `--from gradle`",
            dir.display()
        ))),
        (false, false) => Err(JrsError::usage(format!(
            "nothing to migrate in {}\n\n\
             looked for: pom.xml, build.gradle, build.gradle.kts",
            dir.display()
        ))),
    }
}

/// Read the build files in `dir` and produce a manifest, without writing anything.
pub fn plan(dir: &Path, from: Option<Source>) -> Result<Migration> {
    let (source, file) = match from {
        None => detect(dir)?,
        Some(Source::Maven) => {
            let pom = dir.join("pom.xml");
            if !pom.is_file() {
                return Err(JrsError::usage(format!("no pom.xml in {}", dir.display())));
            }
            (Source::Maven, pom)
        }
        Some(Source::Gradle) => {
            let kts = dir.join("build.gradle.kts");
            let groovy = dir.join("build.gradle");
            let file = if groovy.is_file() {
                groovy
            } else if kts.is_file() {
                kts
            } else {
                return Err(JrsError::usage(format!(
                    "no build.gradle or build.gradle.kts in {}",
                    dir.display()
                )));
            };
            (Source::Gradle, file)
        }
    };

    match source {
        Source::Maven => maven::migrate(&file, dir),
        Source::Gradle => gradle::migrate(&file, dir),
    }
}

/// Write the manifest. Returns the path written, or `None` for a dry run.
///
/// Migration never deletes files and never writes outside the project root.
pub fn write(migration: &Migration, dir: &Path, force: bool) -> Result<Option<PathBuf>> {
    let target = dir.join(MANIFEST_FILE);
    if target.exists() && !force {
        return Err(JrsError::usage(format!(
            "{} already exists\n\npass --force to overwrite it, or --dry-run to see \
             what would be written",
            target.display()
        )));
    }
    std::fs::write(&target, migration.render_manifest()).path(&target)?;
    Ok(Some(target))
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Dir {
        path: PathBuf,
    }

    impl Dir {
        fn new(name: &str) -> Dir {
            let path =
                std::env::temp_dir().join(format!("jrs-migrate-{name}-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&path);
            std::fs::create_dir_all(&path).unwrap();
            Dir { path }
        }

        fn write(&self, name: &str, contents: &str) {
            let file = self.path.join(name);
            std::fs::create_dir_all(file.parent().unwrap()).unwrap();
            std::fs::write(file, contents).unwrap();
        }
    }

    impl Drop for Dir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }

    const MINIMAL_POM: &str = "<project><groupId>g</groupId><artifactId>app</artifactId>\
                               <version>1.0.0</version></project>";

    #[test]
    fn detection_prefers_whichever_build_file_is_present() {
        let dir = Dir::new("detect-maven");
        dir.write("pom.xml", MINIMAL_POM);
        assert_eq!(detect(&dir.path).unwrap().0, Source::Maven);

        let dir = Dir::new("detect-gradle");
        dir.write("build.gradle", "");
        assert_eq!(detect(&dir.path).unwrap().0, Source::Gradle);

        let dir = Dir::new("detect-kts");
        dir.write("build.gradle.kts", "");
        let (source, file) = detect(&dir.path).unwrap();
        assert_eq!(source, Source::Gradle);
        assert!(file.ends_with("build.gradle.kts"));
    }

    #[test]
    fn two_build_systems_ask_for_from() {
        let dir = Dir::new("detect-both");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("build.gradle", "");
        let err = detect(&dir.path).unwrap_err().to_string();
        assert!(err.contains("--from maven"), "{err}");
    }

    #[test]
    fn nothing_to_migrate_names_what_was_looked_for() {
        let dir = Dir::new("detect-none");
        let err = detect(&dir.path).unwrap_err().to_string();
        assert!(err.contains("pom.xml"), "{err}");
        assert!(err.contains("build.gradle.kts"), "{err}");
    }

    #[test]
    fn from_overrides_detection() {
        let dir = Dir::new("from-override");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("build.gradle", "version = '9.9.9'");
        let migration = plan(&dir.path, Some(Source::Gradle)).unwrap();
        assert_eq!(migration.source, Source::Gradle);
        assert_eq!(migration.manifest.version, "9.9.9");
    }

    #[test]
    fn an_existing_manifest_is_not_overwritten_without_force() {
        let dir = Dir::new("no-clobber");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("jrs.toml", "# hand written\n");
        let migration = plan(&dir.path, None).unwrap();

        let err = write(&migration, &dir.path, false).unwrap_err().to_string();
        assert!(err.contains("--force"), "{err}");
        assert_eq!(
            std::fs::read_to_string(dir.path.join("jrs.toml")).unwrap(),
            "# hand written\n"
        );

        write(&migration, &dir.path, true).unwrap();
        assert!(
            std::fs::read_to_string(dir.path.join("jrs.toml"))
                .unwrap()
                .contains("name = \"app\"")
        );
    }

    #[test]
    fn the_generated_manifest_names_its_source() {
        let dir = Dir::new("header");
        dir.write("pom.xml", MINIMAL_POM);
        let text = plan(&dir.path, None).unwrap().render_manifest();
        assert!(text.starts_with("# Generated by jrs "), "{text}");
        assert!(text.contains("pom.xml"), "{text}");
    }

    #[test]
    fn the_original_build_file_survives_migration() {
        let dir = Dir::new("untouched");
        dir.write("pom.xml", MINIMAL_POM);
        let migration = plan(&dir.path, None).unwrap();
        write(&migration, &dir.path, false).unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.path.join("pom.xml")).unwrap(),
            MINIMAL_POM
        );
    }
}
