//! One-shot translation from Maven or Gradle into `jrs.toml`.
//!
//! This is deliberately not a compatibility layer (SPEC §11): it runs once,
//! writes one file, prints a report, and is then out of the picture. The original
//! build files are never touched, so a project can keep building with its old
//! tool while the migration is evaluated.

pub mod gradle;
mod gradle_files;
mod gradle_repos;
mod gradle_tasks;
mod gradle_vars;
pub mod maven;
mod maven_profiles;

use std::path::{Path, PathBuf};

use crate::compile::lang::Language;
use crate::error::{IoResultExt, JrsError, Result};
use crate::manifest::{Dependency, LanguageConfig, MANIFEST_FILE, Managed, Manifest};
use crate::resolve::coord::is_range;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    Maven,
    Gradle,
}

impl Source {
    /// `maven` or `gradle`, in any case.
    ///
    /// # Errors
    ///
    /// [`JrsError::Usage`] for any other name.
    pub fn parse(s: &str) -> Result<Source> {
        match s.trim().to_ascii_lowercase().as_str() {
            "maven" => Ok(Source::Maven),
            "gradle" => Ok(Source::Gradle),
            other => Err(JrsError::usage(format!(
                "unknown build system `{other}`; expected `maven` or `gradle`"
            ))),
        }
    }

    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Source::Maven => "Maven",
            Source::Gradle => "Gradle",
        }
    }
}

/// What the translation did, could only do approximately, and refused to guess at.
#[derive(Debug, Default, Clone)]
pub struct Report {
    /// Printed before the three blocks; Gradle uses it to say the translation is
    /// approximate.
    pub preamble: Option<String>,
    pub migrated: Vec<String>,
    pub needs_review: Vec<String>,
    pub not_migrated: Vec<String>,
}

impl Report {
    pub fn migrated(&mut self, what: impl Into<String>) {
        self.migrated.push(what.into());
    }
    pub fn review(&mut self, what: impl Into<String>) {
        self.needs_review.push(what.into());
    }
    pub fn skipped(&mut self, what: impl Into<String>) {
        self.not_migrated.push(what.into());
    }

    /// Add `other`'s lines after this report's own, block by block.
    pub fn append(&mut self, other: Report) {
        self.migrated.extend(other.migrated);
        self.needs_review.extend(other.needs_review);
        self.not_migrated.extend(other.not_migrated);
    }
}

/// A shading plugin's relocation → `[package.relocate]`, checked as the parser
/// checks it. `excludes` are Shade's patterns, dotted or slashed: a class, or a
/// package as `x.*` or `x.**`; any other wildcard is flagged, since jrs matches
/// no globs. `from` names the plugin in the report.
fn add_relocation(
    out: &mut Manifest,
    report: &mut Report,
    from: &str,
    pattern: &str,
    shaded: &str,
    excludes: &[String],
) {
    let pattern = pattern.trim().trim_end_matches('.');
    let shaded = shaded.trim().trim_end_matches('.');
    if out.package.relocate.iter().any(|r| r.from == pattern) {
        report.skipped(format!(
            "{from} — `{pattern}` is relocated more than once; the first is kept"
        ));
        return;
    }
    let mut exclude = Vec::new();
    for raw in excludes {
        let dotted = raw.trim().replace('/', ".");
        let normalized = match dotted
            .strip_suffix(".**")
            .or_else(|| dotted.strip_suffix(".*"))
        {
            Some(package) => format!("{package}.*"),
            None => dotted.clone(),
        };
        if normalized.trim_end_matches(".*").contains(['*', '?']) {
            report.review(format!(
                "{from} — the relocation of `{pattern}` excludes `{raw}`, a pattern jrs cannot \
                 match; name a class, or a package as `<package>.*`"
            ));
            continue;
        }
        exclude.push(normalized);
    }
    match crate::manifest::relocation(pattern, shaded, exclude) {
        Ok(relocation) => {
            let excluding = if relocation.exclude.is_empty() {
                String::new()
            } else {
                format!(", excluding {}", relocation.exclude.join(", "))
            };
            report.migrated(format!(
                "package.relocate.\"{}\" = {}{excluding}",
                relocation.from, relocation.to
            ));
            out.package.relocate.push(relocation);
        }
        Err(e) => report.skipped(format!("{from} relocation — {e}")),
    }
}

#[derive(Debug, Clone)]
pub struct Migration {
    pub source: Source,
    /// The build file the manifest was translated from.
    pub source_file: PathBuf,
    pub manifest: Manifest,
    pub report: Report,
}

impl Migration {
    /// The comment header that goes at the top of the generated manifest.
    #[must_use]
    pub fn header(&self) -> String {
        format!(
            "Generated by jrs {} from {}.\n\
             Review it before relying on it: translation is best-effort, and\n\
             the original build file was left untouched.",
            env!("CARGO_PKG_VERSION"),
            self.source_file.file_name().map_or_else(
                || self.source_file.display().to_string(),
                |n| n.to_string_lossy().into_owned()
            ),
        )
    }

    #[must_use]
    pub fn render_manifest(&self) -> String {
        self.manifest.render(Some(&self.header()))
    }
}

/// Which build system a directory holds (SPEC §11.1).
///
/// # Errors
///
/// [`JrsError::Usage`] if `dir` holds both a `pom.xml` and a Gradle build, or
/// neither.
pub fn detect(dir: &Path) -> Result<(Source, PathBuf)> {
    let pom = dir.join("pom.xml");
    let gradle_groovy = dir.join("build.gradle");
    let gradle_kts = dir.join("build.gradle.kts");

    let maven = pom.is_file();
    let gradle = gradle_groovy.is_file() || gradle_kts.is_file();

    match (maven, gradle) {
        (true, false) => Ok((Source::Maven, pom)),
        (false, true) => Ok((
            Source::Gradle,
            if gradle_groovy.is_file() {
                gradle_groovy
            } else {
                gradle_kts
            },
        )),
        (true, true) => Err(JrsError::usage(format!(
            "{} holds both a pom.xml and a Gradle build\n\n\
             say which one to read: `jrs migrate --from maven` or `--from gradle`",
            dir.display()
        ))),
        (false, false) => Err(JrsError::usage(format!(
            "nothing to migrate in {}\n\n\
             looked for: pom.xml, build.gradle, build.gradle.kts",
            dir.display()
        ))),
    }
}

/// Read the build files in `dir` and produce a manifest, without writing anything.
///
/// # Errors
///
/// [`JrsError::Usage`] if there is no build file to read (none for `from`, or
/// [`detect`] cannot pick one), and whatever [`maven::migrate`] or
/// [`gradle::migrate`] returns for a build file that cannot be read.
pub fn plan(dir: &Path, from: Option<Source>) -> Result<Migration> {
    let (source, file) = match from {
        None => detect(dir)?,
        Some(Source::Maven) => {
            let pom = dir.join("pom.xml");
            if !pom.is_file() {
                return Err(JrsError::usage(format!("no pom.xml in {}", dir.display())));
            }
            (Source::Maven, pom)
        }
        Some(Source::Gradle) => {
            let kts = dir.join("build.gradle.kts");
            let groovy = dir.join("build.gradle");
            let file = if groovy.is_file() {
                groovy
            } else if kts.is_file() {
                kts
            } else {
                return Err(JrsError::usage(format!(
                    "no build.gradle or build.gradle.kts in {}",
                    dir.display()
                )));
            };
            (Source::Gradle, file)
        }
    };

    match source {
        Source::Maven => maven::migrate(&file, dir),
        Source::Gradle => gradle::migrate(&file, dir),
    }
}

/// Write the manifest. Returns the path written, or `None` for a dry run.
///
/// Migration never deletes files and never writes outside the project root.
///
/// # Errors
///
/// [`JrsError::Usage`] if `jrs.toml` already exists and `force` is not set, and
/// [`JrsError::Io`] if it cannot be written.
pub fn write(migration: &Migration, dir: &Path, force: bool) -> Result<Option<PathBuf>> {
    let target = dir.join(MANIFEST_FILE);
    if target.exists() && !force {
        return Err(JrsError::usage(format!(
            "{} already exists\n\npass --force to overwrite it, or --dry-run to see \
             what would be written",
            target.display()
        )));
    }
    std::fs::write(&target, migration.render_manifest()).path(&target)?;
    Ok(Some(target))
}

// ---- JVM languages (JVM_LANGUAGES.md §10) ----------------------------------

/// Where a `[kotlin]` version is read from when the build plugin has none.
const KOTLIN_LIBRARIES: &[(&str, &str)] = &[("org.jetbrains.kotlin", "kotlin-stdlib")];

/// Where a `[scala]` version is read from when the build names none itself:
/// the Scala 3 library first, since a Scala 3 build has the 2.13 one too.
const SCALA_LIBRARIES: &[(&str, &str)] = &[
    ("org.scala-lang", "scala3-library_3"),
    ("org.scala-lang", "scala-library"),
];

/// Where a `[groovy]` version is read from. The `org.codehaus.groovy` group is
/// Groovy 3 and older, which jrs does not drive, so it is looked for only to
/// say so.
const GROOVY_LIBRARIES: &[(&str, &str)] = &[
    ("org.apache.groovy", "groovy"),
    ("org.codehaus.groovy", "groovy"),
];

/// Turn `language` on at `version`, which was read from `from`.
///
/// A version jrs cannot drive gets no table, since the manifest would then not
/// load, and a "Not migrated" line quoting why. Returns whether the table was
/// written.
fn enable_language(
    out: &mut Manifest,
    language: Language,
    version: &str,
    from: &str,
    report: &mut Report,
) -> bool {
    if out.language(language).is_some() {
        return true;
    }
    let key = language.key();
    let version = version.trim();
    let problem = if version.is_empty() || version.contains('$') {
        Some("the version could not be read".to_string())
    } else if is_range(version) {
        Some("a range, and the compiler is pinned at an exact version".to_string())
    } else {
        language.check_version(version).err()
    };
    if let Some(problem) = problem {
        report.skipped(format!(
            "{from} — {} `{version}`: {problem}; no [{key}] table was written",
            language.name()
        ));
        return false;
    }
    out.languages.push(LanguageConfig {
        language,
        version: version.to_string(),
        source_dir: PathBuf::from(format!("src/main/{key}")),
        test_dir: PathBuf::from(format!("src/test/{key}")),
        compiler_args: Vec::new(),
        compiler_jvm_args: Vec::new(),
    });
    out.languages.sort_by_key(|c| c.language);
    report.migrated(format!("[{key}] version = {version} (from {from})"));
    true
}

/// Turn a language on at the version of its runtime library, declared in
/// either table, when the build plugin itself names no version.
fn enable_from_library(out: &mut Manifest, language: Language, from: &str, report: &mut Report) {
    let candidates = match language {
        Language::Kotlin => KOTLIN_LIBRARIES,
        Language::Scala => SCALA_LIBRARIES,
        Language::Groovy => GROOVY_LIBRARIES,
        Language::Java => return,
    };
    let found = candidates.iter().find_map(|(group, artifact)| {
        out.dependencies
            .iter()
            .chain(&out.dev_dependencies)
            .find(|d| d.group == *group && d.artifact == *artifact)
            .map(|d| (format!("{group}:{artifact}"), d.version.clone()))
    });
    match found {
        Some((library, version)) => {
            enable_language(
                out,
                language,
                &version,
                &format!("{from}, at {library}'s version"),
                report,
            );
        }
        None => report.skipped(format!(
            "{from} — no {}:{} dependency to take the {} version from; no [{}] table \
             was written",
            candidates[0].0,
            candidates[0].1,
            language.name(),
            language.key()
        )),
    }
}

/// A Kotlin compiler plugin, by the short name kotlin-maven-plugin's
/// `<compilerPlugins>` or Gradle's `kotlin("plugin.<name>")` gives it. jrs does
/// not pass compiler plugins to kotlinc yet (`JVM_LANGUAGES.md` §14.2), so each
/// is reported with what goes missing without it.
fn report_compiler_plugin(name: &str, from: &str, report: &mut Report) {
    let consequence = match name {
        "all-open" | "allopen" | "spring" => {
            "Kotlin classes stay final, so frameworks that subclass them, such as \
             Spring's proxies, cannot"
        }
        "no-arg" | "noarg" | "jpa" => {
            "classes get no generated no-argument constructor, which JPA needs"
        }
        "kotlinx-serialization" | "serialization" => {
            "@Serializable classes get no generated serializer"
        }
        "kapt" => "annotation processors do not run over Kotlin sources",
        _ => "whatever it generates is missing",
    };
    report.skipped(format!(
        "{from} — Kotlin compiler plugins are not supported yet (JVM_LANGUAGES.md \
         §14.2): {consequence}"
    ));
}

/// Take out the runtime libraries the build declared by hand that a language
/// table now implies (`JVM_LANGUAGES.md` §4.3).
///
/// Only a plain `[dependencies]` entry at the compiler's version goes: it says
/// exactly what the table implies. A `[dev-dependencies]` entry stays, because
/// declaring the library there is what keeps it off the runtime classpath and
/// out of the fat jar. That is the Groovy project with only Spock tests, and
/// dropping its declaration would put Groovy on its runtime. At any other
/// version the entry stays too, since it was chosen, and gets a review line,
/// since kotlinc and scalac reject a library newer than themselves.
fn drop_implied_libraries(out: &mut Manifest, report: &mut Report) {
    let libraries: Vec<(&str, String, &str, &str)> = out
        .languages
        .iter()
        .flat_map(|c| {
            c.language
                .runtime_libraries(&c.version)
                .into_iter()
                .map(|(group, artifact)| (c.language.key(), c.version.clone(), group, artifact))
        })
        .collect();

    for (key, version, group, artifact) in libraries {
        let is_library =
            |d: &Dependency| d.group == group && d.artifact == artifact && d.classifier.is_none();
        if let Some(index) = out.dependencies.iter().position(|d| {
            is_library(d)
                && d.version == version
                && !d.compile_only
                && !d.runtime_only
                && d.exclusions.is_empty()
        }) {
            out.dependencies.remove(index);
            // The dependency pass reported it as migrated; this line replaces
            // that one, rather than contradict it.
            let listed = format!("{group}:{artifact} (");
            report.migrated.retain(|line| !line.starts_with(&listed));
            report.migrated(format!(
                "{group}:{artifact}:{version} — left out of [dependencies]: [{key}] \
                 implies it at that version"
            ));
        }
        for d in out
            .dependencies
            .iter()
            .chain(&out.dev_dependencies)
            .filter(|d| is_library(d) && d.version != version)
        {
            report.review(format!(
                "{group}:{artifact}:{} — kept at the version the build declares, which is \
                 not [{key}]'s {version}; kotlinc and scalac reject a runtime library newer \
                 than themselves, so keep the two in step",
                d.version
            ));
        }
    }
}

// ---- [managed] and Spring Boot (SPEC §8.9) ---------------------------------

/// Where Spring Boot's plugins, starters and BOM live.
const SPRING_BOOT_GROUP: &str = "org.springframework.boot";

/// Import a BOM through `[managed]`, unless it is there already.
fn add_bom(
    out: &mut Manifest,
    group: &str,
    artifact: &str,
    version: &str,
    from: &str,
    report: &mut Report,
) {
    if out
        .managed
        .iter()
        .any(|m| m.group == group && m.artifact == artifact)
    {
        return;
    }
    out.managed.push(Managed::bom(group, artifact, version));
    report.migrated(format!(
        "[managed] {group}:{artifact} = {version}, a BOM (from {from})"
    ));
}

/// Pin a version through `[managed]`, unless something there pins it already.
fn add_managed(out: &mut Manifest, group: &str, artifact: &str, version: &str) -> bool {
    if out
        .managed
        .iter()
        .any(|m| m.group == group && m.artifact == artifact)
    {
        return false;
    }
    out.managed.push(Managed::new(group, artifact, version));
    true
}

/// The BOM Spring Boot's plugins import, at Boot's version: what versions
/// every starter the build leaves unversioned.
fn spring_boot_bom(out: &mut Manifest, version: &str, from: &str, report: &mut Report) {
    add_bom(
        out,
        SPRING_BOOT_GROUP,
        "spring-boot-dependencies",
        version,
        from,
        report,
    );
}

/// Boot's Gradle plugin and its Maven parent both compile with `-parameters`,
/// and Spring reads parameter names at run time (`@PathVariable`, `@Value`
/// on a constructor), so it goes into `java.javac-args`.
fn spring_boot_parameters(out: &mut Manifest, from: &str, report: &mut Report) {
    if out.java.javac_args.iter().any(|a| a == "-parameters") {
        return;
    }
    out.java.javac_args.push("-parameters".to_string());
    report.migrated(format!(
        "java.javac-args += -parameters (from {from}, which compiles with it so that \
         Spring can read parameter names)"
    ));
}

/// Boot's plugins make the `@SpringBootApplication` class the jar's main
/// class when the build names none; so does migration, by reading the main
/// sources. It also says how the runnable jar is built without Boot.
fn spring_boot_application(out: &mut Manifest, from: &str, report: &mut Report) {
    report.review(format!(
        "{from} — `jrs package --fat` builds the runnable jar: one flat jar with Spring's \
         registries merged, not Boot's nested layout and launcher"
    ));
    if out.main_class.is_some() {
        return;
    }
    let mut roots = vec![out.source_dir.clone()];
    roots.extend(out.languages.iter().map(|c| c.source_dir.clone()));
    let mut found = Vec::new();
    for root in roots {
        for file in source_files(&out.root.join(root)) {
            let Ok(text) = std::fs::read_to_string(&file) else {
                continue;
            };
            if !text.contains("@SpringBootApplication") {
                continue;
            }
            let Some(stem) = file.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
                continue;
            };
            let package = text
                .lines()
                .map(str::trim)
                .find_map(|l| l.strip_prefix("package "))
                .map(|p| p.trim_end_matches(';').trim().to_string())
                .filter(|p| !p.is_empty());
            let mut class = match package {
                Some(p) => format!("{p}.{stem}"),
                None => stem,
            };
            // Kotlin's top-level `main` compiles into `<File>Kt`.
            if file.extension().is_some_and(|e| e == "kt") {
                class.push_str("Kt");
            }
            found.push(class);
        }
    }
    match found.as_slice() {
        [] => report.review(
            "no @SpringBootApplication class was found under the main sources; set \
             project.main-class for `jrs run` and `jrs package --fat`",
        ),
        [one] => {
            report.migrated(format!(
                "project.main-class = {one} (the @SpringBootApplication class)"
            ));
            out.main_class = Some(one.clone());
        }
        [first, ..] => {
            report.review(format!(
                "project.main-class = {first} — the first of {} @SpringBootApplication \
                 classes; check it is the one to run",
                found.len()
            ));
            out.main_class = Some(first.clone());
        }
    }
}

/// The `.java`, `.kt`, `.groovy` and `.scala` files under `dir`, sorted.
fn source_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return out;
    };
    let mut entries: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            out.extend(source_files(&path));
        } else if path
            .extension()
            .is_some_and(|e| matches!(e.to_str(), Some("java" | "kt" | "groovy" | "scala")))
        {
            out.push(path);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Dir {
        path: PathBuf,
    }

    impl Dir {
        fn new(name: &str) -> Dir {
            let path =
                std::env::temp_dir().join(format!("jrs-migrate-{name}-{}", std::process::id()));
            let _ = std::fs::remove_dir_all(&path);
            std::fs::create_dir_all(&path).unwrap();
            Dir { path }
        }

        fn write(&self, name: &str, contents: &str) {
            let file = self.path.join(name);
            std::fs::create_dir_all(file.parent().unwrap()).unwrap();
            std::fs::write(file, contents).unwrap();
        }
    }

    impl Drop for Dir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }

    const MINIMAL_POM: &str = "<project><groupId>g</groupId><artifactId>app</artifactId>\
                               <version>1.0.0</version></project>";

    #[test]
    fn detection_prefers_whichever_build_file_is_present() {
        let dir = Dir::new("detect-maven");
        dir.write("pom.xml", MINIMAL_POM);
        assert_eq!(detect(&dir.path).unwrap().0, Source::Maven);

        let dir = Dir::new("detect-gradle");
        dir.write("build.gradle", "");
        assert_eq!(detect(&dir.path).unwrap().0, Source::Gradle);

        let dir = Dir::new("detect-kts");
        dir.write("build.gradle.kts", "");
        let (source, file) = detect(&dir.path).unwrap();
        assert_eq!(source, Source::Gradle);
        assert!(file.ends_with("build.gradle.kts"));
    }

    #[test]
    fn two_build_systems_ask_for_from() {
        let dir = Dir::new("detect-both");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("build.gradle", "");
        let err = detect(&dir.path).unwrap_err().to_string();
        assert!(err.contains("--from maven"), "{err}");
    }

    #[test]
    fn nothing_to_migrate_names_what_was_looked_for() {
        let dir = Dir::new("detect-none");
        let err = detect(&dir.path).unwrap_err().to_string();
        assert!(err.contains("pom.xml"), "{err}");
        assert!(err.contains("build.gradle.kts"), "{err}");
    }

    #[test]
    fn from_overrides_detection() {
        let dir = Dir::new("from-override");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("build.gradle", "version = '9.9.9'");
        let migration = plan(&dir.path, Some(Source::Gradle)).unwrap();
        assert_eq!(migration.source, Source::Gradle);
        assert_eq!(migration.manifest.version, "9.9.9");
    }

    #[test]
    fn an_existing_manifest_is_not_overwritten_without_force() {
        let dir = Dir::new("no-clobber");
        dir.write("pom.xml", MINIMAL_POM);
        dir.write("jrs.toml", "# hand written\n");
        let migration = plan(&dir.path, None).unwrap();

        let err = write(&migration, &dir.path, false).unwrap_err().to_string();
        assert!(err.contains("--force"), "{err}");
        assert_eq!(
            std::fs::read_to_string(dir.path.join("jrs.toml")).unwrap(),
            "# hand written\n"
        );

        write(&migration, &dir.path, true).unwrap();
        assert!(
            std::fs::read_to_string(dir.path.join("jrs.toml"))
                .unwrap()
                .contains("name = \"app\"")
        );
    }

    #[test]
    fn the_generated_manifest_names_its_source() {
        let dir = Dir::new("header");
        dir.write("pom.xml", MINIMAL_POM);
        let text = plan(&dir.path, None).unwrap().render_manifest();
        assert!(text.starts_with("# Generated by jrs "), "{text}");
        assert!(text.contains("pom.xml"), "{text}");
    }

    #[test]
    fn the_original_build_file_survives_migration() {
        let dir = Dir::new("untouched");
        dir.write("pom.xml", MINIMAL_POM);
        let migration = plan(&dir.path, None).unwrap();
        write(&migration, &dir.path, false).unwrap();
        assert_eq!(
            std::fs::read_to_string(dir.path.join("pom.xml")).unwrap(),
            MINIMAL_POM
        );
    }
}
