//! `jrs.lock`: the resolved dependency graph, written down.
//!
//! The lockfile makes builds reproducible and offline-capable (SPEC §4.4). It
//! records coordinates and checksums, but never absolute paths — those are a
//! property of the machine, not of the resolution, and are recomputed from the
//! cache on load.
//!
//! It is regenerated when the manifest's dependency-affecting fields change,
//! which is what `manifest-checksum` is for, or when `jrs update` is run.

use std::fmt::Write as _;
use std::path::Path;

use crate::error::{IoResultExt, JrsError, Result};
use crate::manifest::{Dependency, Manifest};
use crate::resolve::coord::{Coord, Ga};
use crate::resolve::repo::sha256_hex;
use crate::resolve::{Classpath, Resolution, ResolvedPackage};

pub const LOCK_VERSION: u64 = 1;

#[derive(Debug, Clone)]
pub struct Lockfile {
    pub version: u64,
    /// Digest of everything in the manifest that can change resolution.
    pub manifest_checksum: String,
    pub roots: Vec<Ga>,
    pub test_roots: Vec<Ga>,
    pub packages: Vec<ResolvedPackage>,
}

impl Lockfile {
    #[must_use]
    pub fn from_resolution(manifest: &Manifest, resolution: &Resolution) -> Lockfile {
        let mut packages = resolution.packages.clone();
        packages.sort_by(|a, b| a.coord.cmp(&b.coord));
        Lockfile {
            version: LOCK_VERSION,
            manifest_checksum: manifest_checksum(manifest),
            roots: resolution.roots.clone(),
            test_roots: resolution.test_roots.clone(),
            packages,
        }
    }

    /// Turn the lockfile back into a resolution. Jar paths are left empty; the
    /// caller fills them from the cache or by downloading.
    #[must_use]
    pub fn to_resolution(&self) -> Resolution {
        Resolution {
            packages: self.packages.clone(),
            roots: self.roots.clone(),
            test_roots: self.test_roots.clone(),
            warnings: Vec::new(),
            downloaded: 0,
        }
    }

    /// Whether this lockfile still describes `manifest`.
    #[must_use]
    pub fn matches(&self, manifest: &Manifest) -> bool {
        self.version == LOCK_VERSION && self.manifest_checksum == manifest_checksum(manifest)
    }

    /// Read and parse the lockfile at `path`; `Ok(None)` when there is none.
    ///
    /// # Errors
    ///
    /// As for [`Lockfile::parse`], plus [`JrsError::Io`] when the file exists
    /// but cannot be read.
    pub fn load(path: &Path) -> Result<Option<Lockfile>> {
        match std::fs::read_to_string(path) {
            Ok(text) => Lockfile::parse(&text, path).map(Some),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(JrsError::io(path, e)),
        }
    }

    /// Write the rendered lockfile to `path`.
    ///
    /// # Errors
    ///
    /// [`JrsError::Io`] when the file cannot be written.
    pub fn write(&self, path: &Path) -> Result<()> {
        std::fs::write(path, self.render()).path(path)
    }

    /// Parse lockfile `text`; `path` is only for error messages.
    ///
    /// # Errors
    ///
    /// [`JrsError::Resolve`] when `text` is not TOML, its `version` is not
    /// [`LOCK_VERSION`], or a `[[package]]` is not a table or lacks its
    /// `group`, `artifact` or `version`.
    pub fn parse(text: &str, path: &Path) -> Result<Lockfile> {
        let table: toml::Table = toml::from_str(text)
            .map_err(|e| JrsError::resolve(format!("{}: {}", path.display(), e.message())))?;
        // A negative version is as unsupported as a missing one.
        let version = table
            .get("version")
            .and_then(toml::Value::as_integer)
            .and_then(|n| u64::try_from(n).ok())
            .unwrap_or(0);
        if version != LOCK_VERSION {
            return Err(JrsError::resolve(format!(
                "{}: lockfile version {version} is not supported by jrs {} \
                 (expected {LOCK_VERSION})\n\nrun `jrs update` to regenerate it",
                path.display(),
                env!("CARGO_PKG_VERSION"),
            )));
        }

        let packages = table
            .get("package")
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .map(|p| read_package(p, path))
                    .collect::<Result<Vec<_>>>()
            })
            .transpose()?
            .unwrap_or_default();

        Ok(Lockfile {
            version,
            manifest_checksum: table
                .get("manifest-checksum")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
            roots: read_gas(&table, "roots"),
            test_roots: read_gas(&table, "test-roots"),
            packages,
        })
    }

    #[must_use]
    pub fn render(&self) -> String {
        let mut s = String::new();
        s.push_str("# Generated by jrs. Commit this file.\n");
        s.push_str("# It records the exact dependency graph, so the same manifest\n");
        s.push_str("# resolves to the same jars on every machine.\n\n");
        let _ = writeln!(s, "version = {}", self.version);
        let _ = writeln!(s, "manifest-checksum = \"{}\"", self.manifest_checksum);
        let _ = writeln!(s, "roots = {}", render_gas(&self.roots));
        let _ = writeln!(s, "test-roots = {}", render_gas(&self.test_roots));

        for p in &self.packages {
            s.push_str("\n[[package]]\n");
            let _ = writeln!(s, "group = \"{}\"", p.coord.group);
            let _ = writeln!(s, "artifact = \"{}\"", p.coord.artifact);
            let _ = writeln!(s, "version = \"{}\"", p.coord.version);
            if let Some(c) = &p.coord.classifier {
                let _ = writeln!(s, "classifier = \"{c}\"");
            }
            let _ = writeln!(s, "classpath = \"{}\"", p.classpath.as_str());
            let _ = writeln!(s, "packaging = \"{}\"", p.packaging);
            let _ = writeln!(s, "depth = {}", p.depth);
            let _ = writeln!(s, "direct = {}", p.direct);
            if let Some(c) = &p.checksum {
                let _ = writeln!(s, "checksum = \"{c}\"");
            }
            if !p.dependencies.is_empty() {
                let _ = writeln!(s, "dependencies = {}", render_gas(&p.dependencies));
            }
        }
        s
    }
}

fn read_gas(table: &toml::Table, key: &str) -> Vec<Ga> {
    table
        .get(key)
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str())
                .filter_map(Ga::parse)
                .collect()
        })
        .unwrap_or_default()
}

fn render_gas(gas: &[Ga]) -> String {
    let items: Vec<String> = gas.iter().map(|g| format!("\"{g}\"")).collect();
    format!("[{}]", items.join(", "))
}

fn read_package(value: &toml::Value, path: &Path) -> Result<ResolvedPackage> {
    let t = value.as_table().ok_or_else(|| {
        JrsError::resolve(format!("{}: [[package]] must be a table", path.display()))
    })?;
    let field = |name: &str| -> Result<String> {
        t.get(name)
            .and_then(|v| v.as_str())
            .map(str::to_string)
            .ok_or_else(|| {
                JrsError::resolve(format!(
                    "{}: [[package]] is missing `{name}`\n\nrun `jrs update` to regenerate it",
                    path.display()
                ))
            })
    };
    Ok(ResolvedPackage {
        coord: Coord::new(field("group")?, field("artifact")?, field("version")?).with_classifier(
            t.get("classifier")
                .and_then(|v| v.as_str())
                .map(str::to_string),
        ),
        classpath: Classpath::parse(
            t.get("classpath")
                .and_then(|v| v.as_str())
                .unwrap_or("compile"),
        ),
        packaging: t
            .get("packaging")
            .and_then(|v| v.as_str())
            .unwrap_or("jar")
            .to_string(),
        // A negative or oversized depth falls back like a missing one.
        depth: t
            .get("depth")
            .and_then(toml::Value::as_integer)
            .and_then(|n| usize::try_from(n).ok())
            .unwrap_or(1),
        direct: t
            .get("direct")
            .and_then(toml::Value::as_bool)
            .unwrap_or(false),
        dependencies: read_gas(t, "dependencies"),
        jar: None,
        checksum: t
            .get("checksum")
            .and_then(|v| v.as_str())
            .map(str::to_string),
        mediated: false,
    })
}

/// Digest the manifest fields that can change what resolution produces.
///
/// Deliberately narrow: changing `main-class` or `javac-args` must not invalidate
/// a perfectly good lockfile.
#[must_use]
pub fn manifest_checksum(manifest: &Manifest) -> String {
    // The long form's extras are appended only when present, so a lockfile
    // written before they existed still matches the manifest it was made from.
    let line = |d: &Dependency| {
        let mut s = d.to_string();
        for e in &d.exclusions {
            let _ = write!(s, " exclude={e}");
        }
        if d.compile_only {
            s.push_str(" compile-only");
        }
        s
    };
    let mut canonical = String::new();
    for d in &manifest.dependencies {
        let _ = writeln!(canonical, "dep {}", line(d));
    }
    for d in &manifest.dev_dependencies {
        let _ = writeln!(canonical, "dev {}", line(d));
    }
    for r in &manifest.repositories {
        let _ = writeln!(canonical, "repo {} {}", r.name, r.url);
    }
    format!("sha256:{}", sha256_hex(canonical.as_bytes()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn manifest(body: &str) -> Manifest {
        let text = format!("[project]\nname='app'\nversion='1.0.0'\n{body}");
        Manifest::parse(&text, Path::new("/p/jrs.toml"), Path::new("/p")).unwrap()
    }

    fn package(gav: &str, direct: bool, classpath: Classpath) -> ResolvedPackage {
        ResolvedPackage {
            coord: Coord::parse(gav).unwrap(),
            classpath,
            packaging: "jar".into(),
            depth: if direct { 1 } else { 2 },
            direct,
            dependencies: vec![Ga::new("g", "child")],
            jar: Some(PathBuf::from("/cache/whatever.jar")),
            checksum: Some("sha1:abc123".into()),
            mediated: false,
        }
    }

    fn resolution() -> Resolution {
        Resolution {
            packages: vec![
                package("g:a:1.0", true, Classpath::Compile),
                package("g:child:2.0", false, Classpath::Compile),
                package("g:junit:5.0", true, Classpath::Test),
            ],
            roots: vec![Ga::new("g", "a")],
            test_roots: vec![Ga::new("g", "junit")],
            warnings: vec![],
            downloaded: 0,
        }
    }

    #[test]
    fn a_lockfile_round_trips() {
        let m = manifest("[dependencies]\n'g:a'='1.0'\n[dev-dependencies]\n'g:junit'='5.0'");
        let lock = Lockfile::from_resolution(&m, &resolution());
        let text = lock.render();
        let again = Lockfile::parse(&text, Path::new("jrs.lock")).unwrap();

        assert_eq!(again.version, LOCK_VERSION);
        assert_eq!(again.manifest_checksum, lock.manifest_checksum);
        assert_eq!(again.roots, lock.roots);
        assert_eq!(again.test_roots, lock.test_roots);
        assert_eq!(again.packages.len(), 3);

        let a = &again.packages[0];
        assert_eq!(a.coord.to_string(), "g:a:1.0");
        assert!(a.direct);
        assert_eq!(a.classpath, Classpath::Compile);
        assert_eq!(a.checksum.as_deref(), Some("sha1:abc123"));
        assert_eq!(a.dependencies, vec![Ga::new("g", "child")]);
    }

    #[test]
    fn classifiers_and_compile_only_survive_the_round_trip() {
        let m = manifest("[dependencies]\n'g:a'='1.0'");
        let mut r = resolution();
        r.packages[1].coord.classifier = Some("natives-linux".into());
        r.packages[1].classpath = Classpath::Provided;
        r.roots = vec![Ga::new("g", "a").with_classifier(Some("natives-linux".into()))];
        let again = Lockfile::parse(
            &Lockfile::from_resolution(&m, &r).render(),
            Path::new("jrs.lock"),
        )
        .unwrap();
        let child = again
            .packages
            .iter()
            .find(|p| p.coord.artifact == "child")
            .unwrap();
        assert_eq!(child.coord.classifier.as_deref(), Some("natives-linux"));
        assert_eq!(child.classpath, Classpath::Provided);
        assert_eq!(again.roots, r.roots);
    }

    #[test]
    fn no_absolute_paths_are_written_down() {
        let m = manifest("[dependencies]\n'g:a'='1.0'");
        let text = Lockfile::from_resolution(&m, &resolution()).render();
        assert!(
            !text.contains("/cache/"),
            "a lockfile must be machine-independent:\n{text}"
        );
    }

    #[test]
    fn packages_are_written_in_a_stable_order() {
        let m = manifest("[dependencies]\n'g:a'='1.0'");
        let mut shuffled = resolution();
        shuffled.packages.reverse();
        assert_eq!(
            Lockfile::from_resolution(&m, &shuffled).render(),
            Lockfile::from_resolution(&m, &resolution()).render()
        );
    }

    #[test]
    fn the_checksum_tracks_dependency_changes_only() {
        let base = manifest("[dependencies]\n'g:a'='1.0'");
        let same = manifest("main-class='x.Y'\n[dependencies]\n'g:a'='1.0'");
        let bumped = manifest("[dependencies]\n'g:a'='1.1'");
        let added = manifest("[dependencies]\n'g:a'='1.0'\n'g:b'='1.0'");
        let dev = manifest("[dependencies]\n'g:a'='1.0'\n[dev-dependencies]\n'g:t'='1.0'");
        let repo =
            manifest("[dependencies]\n'g:a'='1.0'\n[repositories]\nx='https://example.com/m2'");
        let excluded = manifest("[dependencies]\n'g:a'={version='1.0', exclusions=['x:y']}");
        let compile_only = manifest("[dependencies]\n'g:a'={version='1.0', compile-only=true}");
        let classified = manifest("[dependencies]\n'g:a:natives'='1.0'");

        assert_eq!(manifest_checksum(&base), manifest_checksum(&same));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&excluded));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&compile_only));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&classified));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&bumped));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&added));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&dev));
        assert_ne!(manifest_checksum(&base), manifest_checksum(&repo));
    }

    #[test]
    fn a_stale_lockfile_is_detected() {
        let before = manifest("[dependencies]\n'g:a'='1.0'");
        let lock = Lockfile::from_resolution(&before, &resolution());
        assert!(lock.matches(&before));
        assert!(!lock.matches(&manifest("[dependencies]\n'g:a'='2.0'")));
    }

    #[test]
    fn an_unknown_lockfile_version_says_how_to_recover() {
        let err = Lockfile::parse("version = 99\n", Path::new("jrs.lock"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("jrs update"), "{err}");
    }

    #[test]
    fn a_missing_lockfile_is_not_an_error() {
        let missing = std::env::temp_dir().join("jrs-no-such-lockfile.lock");
        let _ = std::fs::remove_file(&missing);
        assert!(Lockfile::load(&missing).unwrap().is_none());
    }

    #[test]
    fn a_truncated_package_entry_says_how_to_recover() {
        let err = Lockfile::parse(
            "version = 1\n[[package]]\ngroup = \"g\"\n",
            Path::new("jrs.lock"),
        )
        .unwrap_err()
        .to_string();
        assert!(err.contains("artifact"), "{err}");
        assert!(err.contains("jrs update"), "{err}");
    }
}
